# Долгосрочная работа по алгебре. 
# Знакомство с Python и Sage. Применение SVD разложения для нахождения канонических  квадратичных форм над $\mathbb{R}$

В данной работе мы будем применять SVD разложение для поиска канонических квадратичных форм над $\mathbb{R}$. Цель данной работы продемонстрировать эффекты, связанные с точностью вычислений, которые возникают при переходе от конечных полей к полям действительных и комплексных чисел

In [1]:
# необходимые импорты

from IPython.display import HTML

### 1. Нахождение собственных значений матриц

Рассмотрим следующий пример. Пусть $A$ - некоторая квадратная матрица размера $n\times n$ над $\mathbb{R}$, при этом $A=A^T$. Тогда, характеристический многочлен матрицы $A$ раскладывается над $\mathbb{R}$ на линейные множители. Далее будем генерировать случайные симметричные матрицы с известными собственными значениями, вычислять характеристический многочлен данных матриц, а затем вычислять корни.

Из курса алгебры известно, что произвольная симметричная матрица ортогонально подобна диагональной матрице. Используем данный результат для генерирования произвольной симметричной матрицы. Научимся сначала генерировать ортонормированные матрицы. Используя ортогонализацию столбцов Грамма-Шмидта `gram_schmidt()` для произвольной матрицы напишите функцию для генерирования ортонормированной матрицы.

In [2]:
# подсказка
A  = random_matrix(RDF, 3)
print(A)
print()

B,C = A.gram_schmidt()
print(B)
print()

print(C)
print()

print(B*B.transpose())
print()

print(C*C.transpose())
print()

[  -0.6968197015411661    0.4812427876589347    0.4925217532276309]
[-0.007049254609466038   -0.4578285739085266    0.6394494210697172]
[  -0.1853450349275858   -0.8737564649133587  0.058981661352832226]

[-0.7112886638175904 0.49123544964170884   0.502748614856267]
[0.08361923635430371 -0.6510335167133533  0.7544290446605078]
[ 0.6979084897292123  0.5786562823742187 0.42199602703430555]

[ 0.9796581008352259                 0.0                 0.0]
[0.10159474024274186  0.7798915090825587                 0.0]
[-0.2677333791331388  0.5978438122477719  -0.610068514333545]

[                   1.0 1.6370032736151627e-17 3.8345050908110334e-17]
[1.6370032736151627e-17     0.9999999999999993  2.913945382144614e-16]
[3.8345050908110334e-17  2.913945382144614e-16     0.9999999999999999]

[ 0.9597299945320815 0.09952811028105259 -0.2622871737317683]
[0.09952811028105259  0.6185522571840609   0.439053009822242]
[-0.2622871737317683   0.439053009822242  0.8012819783261371]



In [3]:
def generate_orthonormal_matrix(n):
    """
    generates random orthonormal n x n matrix over R
    """
    A = random_matrix(RDF, n)
    B, C = A.gram_schmidt() 
    ans = B# YOUR CODE HERE
    return  ans

In [4]:
def gen_random_symm_matix_with_given_eig_values(eig_values):
    D = diagonal_matrix(RDF, eig_values) # генерируем диагональную матрицу используя функцию diagonal_matrix
    n = len(eig_values) # число элементов в списке
    C = generate_orthonormal_matrix(n) # генерируем ортонормированную матрицу используя ортогонализацию Грамма-Шмидта
    return C**(-1)*D*C 
    

Убедимся что все работает

In [5]:
gen_random_symm_matix_with_given_eig_values([1,2])

[  1.1077569832830743 -0.31007324269727893]
[  -0.310073242697279   1.8922430167169253]

Действительно, матрица симметричная. Проверим для больших значений $n$, где $n$ размер матрицы

In [6]:
gen_random_symm_matix_with_given_eig_values([1,2,3,4])

[  2.7692233494066945  -0.2494684118859745   0.5803674608249921  0.27881134083756237]
[-0.24946841188597435    2.655659869285323   0.5543094019294091   0.9587944520114278]
[  0.5803674608249919   0.5543094019294089   1.4828370007132656  0.23578398511407064]
[ 0.27881134083756237   0.9587944520114278   0.2357839851140707   3.0922797805947173]

Далее убедимся, что матрица действительно имеет нужные собственные значения

In [7]:
A = gen_random_symm_matix_with_given_eig_values([1,2,3,4])
char_pol_a = A.characteristic_polynomial()
char_pol_a

x^4 - 10.0*x^3 + 35.0*x^2 - 50.000000000000014*x + 24.000000000000057

In [8]:
char_pol_a.factor()

(x - 3.9999999999999973) * (x - 3.0000000000000178) * (x - 1.9999999999999787) * (x - 1.0000000000000084)

### 1.1 Случай больших матриц

На первый взгляд метод нахождения собственных значений довольно точный. Рассмотрим данный метод на примере нахождения собственных значений болших матриц. Сгенерируем матрицу с собственными значениями от 0 до 19. 

In [9]:
eig_values = [i for i in range(20)] # [0,1,2,...19]
A = gen_random_symm_matix_with_given_eig_values(eig_values)
A

20 x 20 dense matrix over Real Double Field (use the '.str()' method to see the entries)

Далее вычислим разложение характеристического многочлена

In [10]:
for el in A.characteristic_polynomial().factor():
    print(el)

(x - 18.99985998923343, 1)
(x - 18.001322906835156, 1)
(x - 16.994183439646264, 1)
(x - 16.015108747168053, 1)
(x - 14.972466537131169, 1)
(x - 14.03380066097563, 1)
(x - 12.972012182927209, 1)
(x - 12.012059632985713, 1)
(x - 11.007488985457075, 1)
(x - 9.977905742235817, 1)
(x - 9.02724110440259, 1)
(x - 7.9754257169199985, 1)
(x - 7.017825594562305, 1)
(x - 5.989960642476747, 1)
(x - 5.0045667460269225, 1)
(x - 3.9984379351380346, 1)
(x - 3.000394497949316, 1)
(x - 1.9999322928285848, 1)
(x - 1.0000069562457332, 1)
(x + 3.1114574071954224e-07, 1)


Кажется, что метод вполне приемлем, хотя уже хдесь наблюдается потеря в точности по сравнению с предыдущим примером.

Рассмотрим случай $n=100$. Выполнение следующей ячейки может занять длительное время, а результат может быть совершенно иным (это связано с тем, что мы генерируем матрицы случайно)

In [11]:
A = gen_random_symm_matix_with_given_eig_values([i for i in range(100)])
for el in A.characteristic_polynomial().factor():
    print(el)

(x - 228.13565970154158, 1)
(x - 114.73292754655475, 1)
(x - 42.933639124530785, 1)
(x + 51.75128633054149, 1)
(x^2 - 725.4337712227613*x + 133898.1665476801, 1)
(x^2 - 643.0293820848862*x + 120601.13633124542, 1)
(x^2 - 512.0339106049441*x + 98435.56672024413, 1)
(x^2 - 377.56439874951315*x + 74387.967883278, 1)
(x^2 - 268.9682665513905*x + 53807.99067380447, 1)
(x^2 - 215.2351071342713*x + 13388.370843034076, 1)
(x^2 - 192.20887995330025*x + 38415.29718633802, 1)
(x^2 - 181.92081716813453*x + 8283.462667779952, 1)
(x^2 - 180.6858002835762*x + 8289.30295851257, 1)
(x^2 - 177.35611961765863*x + 8262.522777128695, 1)
(x^2 - 172.1981296178782*x + 8234.466948208017, 1)
(x^2 - 169.76710741576517*x + 11059.648382270447, 1)
(x^2 - 166.01486842922776*x + 8256.80813543055, 1)
(x^2 - 157.6718015942971*x + 8237.982701437903, 1)
(x^2 - 152.78351095350934*x + 13563.90116616603, 1)
(x^2 - 147.4196905386075*x + 8206.134903021717, 1)
(x^2 - 140.99794515920888*x + 27516.364295765765, 1)
(x^2 - 135.921

Таким образом, мы видим, что уже для матриц 100 на 100 данный метод абсолютно неприменим.

### 1.2. Случай кратных собственных значений

Однако проблемы могут возникнуть не только при росте $n$. Ранее мы рассматривали только матрицы с различными собственными значениями. Рассмотрим случай кратных собственных значений.

Напомним, что два списка в Python мажно сконкатенировать, используя операцию $+$

In [12]:
[1,2]+[100, 200]

[1, 2, 100, 200]

Также можно использовать операцию * для повторения списка (**будьте аккуратны с этой операцией**)

In [13]:
eig_values = [1]*10 + [2]
eig_values

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]

Далее 5 раз будем генерировать матрицу с указанными СЗ и смотреть на разложение ХМ

In [14]:
for i in range(5):
    A = gen_random_symm_matix_with_given_eig_values(eig_values)
    for el in A.characteristic_polynomial().factor():
        print(el)
    print()

(x - 1.9999999999911906, 1)
(x - 1.0608298612675793, 1)
(x - 0.9427820901654547, 1)
(x^2 - 2.0965871004382626*x + 1.1002452522340782, 1)
(x^2 - 2.0335456452014253*x + 1.0370959327191076, 1)
(x^2 - 1.960630804209936*x + 0.964050540763374, 1)
(x^2 - 1.9056244987261546*x + 0.9089389270146455, 1)

(x - 1.9999999999826836, 1)
(x^2 - 2.1173582298640183*x + 1.121169143280057, 1)
(x^2 - 2.0719131891707754*x + 1.0757150013726386, 1)
(x^2 - 1.998877307519757*x + 1.0026459376164987, 1)
(x^2 - 1.927444015400006*x + 0.9311640008699591, 1)
(x^2 - 1.8844072580627729*x + 0.8880918039717336, 1)

(x - 1.999999999965946, 1)
(x - 1.061745773448254, 1)
(x - 0.9426627522751815, 1)
(x^2 - 2.0974706557437917*x + 1.1012241475889093, 1)
(x^2 - 2.033032231463163*x + 1.0366417100077312, 1)
(x^2 - 1.9598645025583097*x + 0.963313516563518, 1)
(x^2 - 1.9052240845453685*x + 0.9085546450499467, 1)

(x - 1.999999999997118, 1)
(x - 1.0511594567051543, 1)
(x - 1.016525989775121, 1)
(x^2 - 2.076931954605353*x + 1.07962733

Видим, что собственное значение $2$ определяется неплохо, в то время как собственное значение $1$ определяется не всегда и с очень низкой точностью.

### 1.3 Использование специализированных алгоритмов

Таким образом выше показано, что использование прямолинейных алгоритмов, работающих для матриц над конечными полями (которые замечательно работают в теории) подчас неприемлемо при работе с действительными матрицами. На практике для поиска собственных значений используются [алгоритмы](https://en.wikipedia.org/wiki/QR_algorithm) базирующиеся на [QR разложении](https://en.wikipedia.org/wiki/QR_decomposition). Которые уже реализованы в sage

Для нахождения собственных значений необходимо вызвать функцию `A.eigenvalues()`. Напомним, что чтобы отсортировать список можно использовать функцию `sorted` 

In [15]:
eig_values = [i for i in range(20)] # [0,1,2,...19]
A = gen_random_symm_matix_with_given_eig_values(eig_values)
sorted(A.eigenvalues()) 

[5.562653515524529e-15,
 0.9999999999999983,
 1.999999999999997,
 3.000000000000006,
 3.999999999999997,
 5.000000000000001,
 5.999999999999995,
 6.999999999999997,
 8.000000000000002,
 9.000000000000005,
 10.000000000000005,
 11.000000000000012,
 12.000000000000007,
 13.000000000000002,
 13.99999999999998,
 14.999999999999984,
 15.99999999999995,
 17.000000000000032,
 17.999999999999996,
 18.999999999999954]

Видно что точность, гораздо более высокая. Рассмотрим пример с кратными собственными значениями

In [16]:
eig_values = [1]*10 + [2]
eig_values

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]

In [17]:
for i in range(5):
    A = gen_random_symm_matix_with_given_eig_values(eig_values)
    for el in sorted(A.eigenvalues()):
        print(el)
    print('-'*50) # создаем удобное разделение 
    #print()

0.9999999999999989
0.9999999999999994
0.9999999999999997
0.9999999999999998
0.9999999999999999
1.0
1.0
1.0
1.0000000000000002
1.0000000000000004
1.9999999999999998
--------------------------------------------------
0.9999999999999994
0.9999999999999997
0.9999999999999998
0.9999999999999999
0.9999999999999999
1.0
1.0
1.0000000000000002
1.0000000000000002
1.0000000000000004
2.0
--------------------------------------------------
0.9999999999999996
0.9999999999999999
1.0
1.0
1.0000000000000002 - 1.1072955152209595e-16*I
1.0000000000000002
1.0000000000000002 + 1.1072955152209595e-16*I
1.0000000000000004
1.0000000000000007
1.0000000000000009
2.0
--------------------------------------------------
0.9999999999999993
0.9999999999999996
0.9999999999999996
0.9999999999999998
0.9999999999999999
0.9999999999999999
1.0
1.0000000000000002
1.0000000000000002
1.0000000000000002
1.999999999999999
--------------------------------------------------
0.9999999999999996
0.9999999999999998
0.9999999999999999


Видим, что точность тоже очень высокая, при этом также видим, что иногда могут возникать комплексные числа.

### Исследуйте нексолько (не менее 5) различных матриц с различными вариантами для собственных значений и выведите данные собственные значения. Рассмотрите случай больших матриц ($n\approx 200,300,1000$)

In [83]:
# YOUR CODE HERE

## 2 Нахождение нормальных квадратичных форм

Из предыдущих примеров видно, что при нахождении собственных значений матриц кратные собственные значения находятся по несколько раз. Так например, для матрицы $A$ с собственным значением 1 кратности $10$ и 2 кратности $1$ имеем

In [18]:
eig_values = [1]*10 + [2]
eig_values
A = gen_random_symm_matix_with_given_eig_values(eig_values)
for el in sorted(A.eigenvalues()):
    print(el)

0.9999999999999993
0.9999999999999994
0.9999999999999997
0.9999999999999998
0.9999999999999999
1.0
1.0
1.0
1.0000000000000002
1.0000000000000002
1.9999999999999998


Видим, что для сосбственного значения 1 возникли различные значения. Ниже предлагается написать функцию, которая будет по списку найденных  собственных значений находить собственные значения учетом поправок неточности. А именно, будем считать, что все собственные значения действительные числа (как показывают результаты выше мнимая часть также может возникать) а также будем считать, что СЗ совпадают если модуль из разности не превосходит некоторого порога, например $10^{-7}$

**Напишите функцию для нахождения собственных значений с учетом кратности**
(если не справитесь сами ниже она реализована за вас)

In [19]:
def find_eigen_vals_with_muls(mat, thr = 1e-7):
    """
    mat --- square symmetric matix over R
    thr --- threshhold. two values are equal if absolute value of  their difference is not greate thr
    return: list of pairs (eigen_value, multiplicity)
    """
    # YOUR CODE HERE
    pass

In [48]:
# Specific code we want to hide:
# ==============================
# @hidden
def find_eigen_vals_with_muls(mat, thr = 1e-7):
    """
    mat --- square symmetric matix over R
    return: list of pairs (eigen_value, multiplicity)
    """
    eigen_values = mat.eigenvalues()
    eigen_values = [el.real() for el in eigen_values] # берем только действительную часть
    eigen_values = sorted(eigen_values) 
    
    cur_val = eigen_values[0]
    cur_mul = 1
    idx = 0
    ans = []
    
    while idx + 1  < len(eigen_values):
        if eigen_values[idx + 1] - cur_val < thr:
            cur_mul += 1
            idx += 1
        else:
            ans.append((cur_val, cur_mul))
            idx += 1
            cur_val = eigen_values[idx]
            cur_mul = 1


    ans.append((cur_val, cur_mul))
    return ans
# ==============================

# Necessary script to hide the cell:
# ==============================
HTML('''<script>
  code_show=true; 
  function code_toggle() {
    if (code_show){
        $('.cm-comment:contains(@hidden)').closest('div.input').hide();
    } else {
        $('.cm-comment:contains(@hidden)').closest('div.input').show();
    }
    code_show = !code_show
  } 
  $( document ).ready(code_toggle);
</script>
Подсмотреть подсказку: <a href="javascript:code_toggle()">тык</a>.''')
# ==============================

In [21]:
eig_values = [1]*10 + [2]
A = gen_random_symm_matix_with_given_eig_values(eig_values)
find_eigen_vals_with_muls(A)

[(0.9999999999999996, 10), (2.0000000000000004, 1)]

Протестируем данную функцию. 

In [22]:
eig_values = [-1]*2 + [0]*3 + [1]*4 + [100]*13
A = gen_random_symm_matix_with_given_eig_values(eig_values)
find_eigen_vals_with_muls(A, thr = 1e-7)

[(-1.000000000000006, 2),
 (-9.619152063201963e-16, 3),
 (0.9999999999999952, 4),
 (99.9999999999999, 13)]

Далее нам понадобится решать СЛУ (СОЛУ) а также работать с матрицами и отдельными их элементами и частями. Напомним как это делать

### Работа с матрицами в sage

Создадим произвольную матрицу 

In [23]:
A = matrix(RDF,
          [
              [0,1,2,3],
              [4,5,6,7],
              [8,9,19,11]
          ]
          )
A

[ 0.0  1.0  2.0  3.0]
[ 4.0  5.0  6.0  7.0]
[ 8.0  9.0 19.0 11.0]

In [24]:
A.nrows()

3

In [25]:
A.ncols()

4

Далее напомним как осуществлять доступ к строкам и столбцам матрицы

In [26]:
A[0] # первая строка

(0.0, 1.0, 2.0, 3.0)

In [27]:
A[2]

(8.0, 9.0, 19.0, 11.0)

In [28]:
A[-1] # --- последняя строка

(8.0, 9.0, 19.0, 11.0)

Обратите внимание на тип

In [29]:
type(A[0])

<class 'sage.modules.vector_real_double_dense.Vector_real_double_dense'>

Данная штука имеет тип `Vector_real_double_dense`

Чтобы получить матрицу размера $1\times n$ нужно написать

In [30]:
A[0, :]

[0.0 1.0 2.0 3.0]

Формально это означает подматрица состоящая из первой строки и всех столбцов. Проверим тип

In [31]:
type(A[0, :])

<class 'sage.matrix.matrix_real_double_dense.Matrix_real_double_dense'>

Это же можно записать как 

In [107]:
A[0:1]

[0.0 1.0 2.0 3.0]

данная нотация является весьма удобной ~~поначалу бошка плывет, но потом привыкаешь~~  и широкораспространенной в библиотеках научных вычислений numpy, scipy, torch...

Далее покажем как можно взять подматрицу состояющую из первых двух строк

In [86]:
A[0:2]

[0.0 1.0 2.0 3.0]
[4.0 5.0 6.0 7.0]

Нулевой элемент обычно не пишут, поэтому можно писать так

In [87]:
A[:2]

[0.0 1.0 2.0 3.0]
[4.0 5.0 6.0 7.0]

Это же можно записать как


In [108]:
A[0:2, :]

[0.0 1.0 2.0 3.0]
[4.0 5.0 6.0 7.0]

Далее создадим подматрицу из **последних** двух строк. То есть строк с номерами 2 и 3

In [88]:
A[-2:]

[ 4.0  5.0  6.0  7.0]
[ 8.0  9.0 19.0 11.0]

Далее покажем как можно осуществлять доступ к столбцам матрицы A

In [89]:
A[:, 0] # первый столбец 

[0.0]
[4.0]
[8.0]

In [90]:
A[:, 1] # второй столбец 

[1.0]
[5.0]
[9.0]

In [92]:
A[:, 2] # третий столбец 

[ 2.0]
[ 6.0]
[19.0]

In [94]:
A[:, 3] # четвертый столбец 

[ 3.0]
[ 7.0]
[11.0]

In [96]:
A[:, -1] # последний столбец 

[ 3.0]
[ 7.0]
[11.0]

Можно брать подматрицы

In [109]:
A[1:3, 2:4]

[ 6.0  7.0]
[19.0 11.0]

Это же равносильно

In [110]:
A[1:, 2:]

[ 6.0  7.0]
[19.0 11.0]

Пока что этого достаточно. При желании всегда можно использовать что-то типа такого для создания подматриц

In [113]:
B = zero_matrix(2,2)
rows = [1,2]
cols =  [2,3]
for i in range(len(rows)):
    for j in range(len(cols)):
        B[i,j] = A[rows[i], cols[j]]
B

[ 6  7]
[19 11]

In [115]:
A[1:3, 2:4]

[ 6.0  7.0]
[19.0 11.0]

Здесь же отметим про функцию `enumerate`

In [117]:
for el in enumerate([100,300,500, 900]):
    print(el)

(0, 100)
(1, 300)
(2, 500)
(3, 900)


С ее помощью код выше можно переписать в виде

In [118]:
B = zero_matrix(2,2)
rows = [1,2]
cols =  [2,3]
for i,row in enumerate(rows) :
    for j, col in enumerate(cols):
        B[i,j] = A[row, col]
B

[ 6  7]
[19 11]

### Применение SVD для нахождения собственных векторов

Рассмотрим пример

In [32]:
eig_values = [3]*2 + [7]
A = gen_random_symm_matix_with_given_eig_values(eig_values)
A

[ 4.3630389363251325 -1.1488709360478133   1.508103502968812]
[ -1.148870936047813   3.968354162540618 -1.2711421786556176]
[ 1.5081035029688121  -1.271142178655618  4.6686069011342495]

Далее вызовем реализованную собственную функцию для нахождения собственных значений

In [33]:
find_eigen_vals_with_muls(A)

[(3.0, 2), (6.999999999999999, 1)]

Далее решим СЛУ

$$
(E\cdot 3 - A)x = 0
$$

В теории ФСР данной СОЛУ имеет $2$ вектора. Проверим это

In [34]:
(identity_matrix(A.nrows())*3 - A).right_kernel()

Vector space of degree 3 and dimension 0 over Real Double Field
Basis matrix:
[]

Видим, что в данном случае СОЛУ не имеет решений! Это опять же связано с тем, что при работе с действительными матрицами нужно учитывать точность

Рассмотрим SVD разложение  $E\cdot 3 - A = U\Sigma V^T$

In [35]:
u, s, v = (identity_matrix(A.nrows())*3 - A).SVD()

Выполним проверку

In [36]:
(identity_matrix(A.nrows())*3 - A)

[-1.3630389363251325  1.1488709360478133  -1.508103502968812]
[  1.148870936047813  -0.968354162540618  1.2711421786556176]
[-1.5081035029688121   1.271142178655618 -1.6686069011342495]

In [37]:
u*s*v.transpose()

[-1.3630389363251325  1.1488709360478122 -1.5081035029688103]
[ 1.1488709360478129 -0.9683541625406175   1.271142178655617]
[ -1.508103502968812  1.2711421786556172 -1.6686069011342484]

Далее посмотрим на матрицу $\Sigma$

In [38]:
s

[   3.9999999999999987                   0.0                   0.0]
[                  0.0 9.434632709621008e-16                   0.0]
[                  0.0                   0.0 2.440448096623972e-16]

Мы видим, что последние 2 диагональных значения очень близки к нулю. Тем не менее формально они ненулевые и матрица s обратима. Именно из-за этого наивный метод `right_kernel()` выдавал отсутствие решений

Далее отметим, что
$$
(E\cdot 3 - A)V = U\Sigma
$$
Следовательно
$$
(E\cdot 3 - A)V_{2} = \sigma_2U_2 \approx 
\begin{pmatrix}
0 \\
0 \\
0
\end{pmatrix}
$$

и аналогично
$$
(E\cdot 3 - A)V_{3} = \sigma_3U_3 \approx 
\begin{pmatrix}
0 \\
0 \\
0
\end{pmatrix}
$$

Таки образом ФСР будет $V_2, V_3$ то есть

In [39]:
v[:, -2], v[:, -1] # взяли предпоследний столбец и последний

(
[ 0.6142300024041938]  [ -0.5310007251080368]
[-0.2526259475587791]  [ -0.8331215937574026]
[-0.7475972410105413], [-0.15474701919541045]
)

Объясните почему  данные столбцы всегда линейно-независимы (вспомните свойства SVD)

In [ ]:
### YOUR CODE HERE

Проверим, корректность


In [40]:
(identity_matrix(A.nrows())*3 - A)*v[:, -1]

[-2.407142563621386e-16]
[2.0468032427124334e-16]
[1.5679647164071595e-16]

In [41]:
(identity_matrix(A.nrows())*3 - A)*v[:, -2]

[ 9.384060736438424e-17]
[-6.801311270955787e-17]
[1.0064433567818124e-15]

Далее покажем, как для матрицы симметричной матрицы $A$, найти матрицу $C$, такую что $C^{-1} = C^T$ и
$$
C^{-1}AC = D = diag[d_1,\ldots, d_n]
$$

**Используя идеи выше реализуйте функцию для нахождения матрицы C** (снизу есть подсказка)

In [ ]:
def find_normal_base_for_mat(mat):
    # YOUR CODE HERE
    # 1. create matrix for answer 
    # 2. find eigenvalues with multiplicities
    # 3. Solve systems using SVD
    # 4. form answer using last coluns of matrix V from SVD
    pass


In [47]:
#@hidden
def find_normal_base_for_mat(mat):
    n = mat.nrows()
    ans =  zero_matrix(RDF, n, n) # матрица для ответа
    
    eig_vals_with_muls = find_eigen_vals_with_muls(mat) # находим собственные значения с учетом кратности
    cur_column = 0
    for val, mul in eig_vals_with_muls: 
        char_mat = -mat + val * identity_matrix(n) #  Er - A
        
        u,s,v = char_mat.SVD() # char_mat = u*s*v^T
        ans[:, cur_column: cur_column + mul] = v[:, -mul:]
        cur_column += mul
    return ans


# Necessary script to hide the cell:
# ==============================
HTML('''<script>
  code_show=true; 
  function code_toggle() {
    if (code_show){
        $('.cm-comment:contains(@hidden)').closest('div.input').hide();
    } else {
        $('.cm-comment:contains(@hidden)').closest('div.input').show();
    }
    code_show = !code_show
  } 
  $( document ).ready(code_toggle);
</script>
Подсмотреть подсказку: <a href="javascript:code_toggle()">тык</a>.''')
# ==============================

Протестируем данную функцию

In [43]:
eig_values = [-1]*2 + [120]*2
A = gen_random_symm_matix_with_given_eig_values(eig_values)

C = find_normal_base_for_mat(A)

In [44]:
C.transpose() *A *C

[    -1.0000000000000038   9.500276822952902e-16   4.423523066952856e-14   8.541935952969547e-14]
[  2.279871032834202e-15     -0.9999999999999952   9.132441929392285e-15 -1.3973990151094902e-14]
[ 3.6295980061172874e-14   3.846138685550951e-15      120.00000000000006  -7.658009477312555e-16]
[ 5.5563025794160343e-14 -1.3543737517501688e-14  1.5054637763094715e-14                   120.0]

In [45]:
C.transpose() * C

[     0.9999999999999999  -1.527127734354331e-17   5.546513031296696e-16   7.673015813225855e-16]
[ -1.527127734354331e-17      0.9999999999999999   5.061066899269963e-16 -1.5319548217300506e-16]
[  5.546513031296696e-16   5.061066899269963e-16      1.0000000000000004    8.47166252506106e-17]
[  7.673015813225855e-16 -1.5319548217300506e-16    8.47166252506106e-17                     1.0]

**Протестируйте код на матрицах большего размера. Рассмотрите различные примеры, не менее 5**

In [153]:
#YOUR CODE HERE

In [62]:
def generate_normal_matrix_11(a):
     return matrix(RDF, [
        [a]
    ])

def generate_normal_matrix_22(a,b):
    return matrix(RDF, [
        [a,b],
        [-b, a]
    ])

In [108]:
A = block_diagonal_matrix(generate_normal_matrix_22(3,4),
                          generate_normal_matrix_22(3,4),
                          generate_normal_matrix_22(3,4),
                          generate_normal_matrix_22(1,2),
                          generate_normal_matrix_11(10)
                         )

In [109]:
C = generate_orthonormal_matrix(A.nrows())
A = C^(-1)*A*C

In [111]:
#A

In [112]:
A.eigenvalues()

[10.000000000000007,
 1.0000000000000007 + 1.9999999999999991*I,
 1.0000000000000007 - 1.9999999999999991*I,
 2.999999999999999 + 4.0*I,
 2.999999999999999 - 4.0*I,
 3.0 + 4.000000000000001*I,
 3.0 - 4.000000000000001*I,
 2.9999999999999987 + 3.9999999999999996*I,
 2.9999999999999987 - 3.9999999999999996*I]

In [123]:
def find_complex_eigen_vals_with_muls(mat, thr = 1e-8):
    eigen_vals = A.eigenvalues()
    clusters = []
    marked = set()
    for i, ei in enumerate(eigen_vals):
        if i in marked:
            continue
        cluster = [ei]
        marked.add(i)
        for j, ej in enumerate(eigen_vals):
            if i == j or j in marked:
                continue
            if abs(ei - ej) < thr:
                cluster.append(ej)
                marked.add(j)
        clusters.append(cluster)
    return clusters
                
     
def find_pairs_of_conj_eigvals(mat, thr = 1e-8):
    eigen_vals = A.eigenvalues()
    clusters = []
    marked = set()
    for i, ei in enumerate(eigen_vals):
        if i in marked:
            continue
        cluster = [ei]
        marked.add(i)
        for j, ej in enumerate(eigen_vals):
            if i == j or j in marked:
                continue
            if abs(ei.real() - ej.real()) < thr and abs(ei.imag() + ej.imag()) < thr:
                cluster.append(ej)
                marked.add(j)
                break
        clusters.append(cluster)
    return clusters
                

    
def factor_char_pol_for_normal_matrix(mat, thr = 1e-6):
    S = CDF
    Sx = PolynomialRing(S, 'x')
    x = Sx([0,1])
    factors = []
    for el in find_pairs_of_conj_eigvals(mat):
        if len(el) == 1:
            factors.append(x - el[0])
            continue
        factors.append((x-el[0])*(x-el[1]))
    
    factors_with_mults = []
    marked = set()
    for i,fi in enumerate(factors):
        if i in marked:
            continue
        else:
            marked.add(i)
            cur = fi
            mult = 1
        for j, fj in enumerate(factors):
            if i == j or j in marked:
                continue
            if sum(abs(el) for el in (fi-fj).list()) < thr:
                mult += 1
                marked.add(j)
        factors_with_mults.append((fi, mult))
    return factors_with_mults
 
def val_of_pol_on_mat(mat, pol):
    ans = zero_matrix(mat.nrows())
    for i,c in enumerate(pol.list()):
        ans += c*mat**i
    return ans
    

In [118]:
factor_char_pol_for_normal_matrix(A)

[(x - 10.000000000000007, 1),
 (x^2 - 2.0000000000000013*x + 4.999999999999998, 1),
 (x^2 - 5.999999999999998*x + 24.999999999999993, 3)]

In [119]:
A.characteristic_polynomial().factor()

(x - 10.000000000000046) * (x^2 - 6.000140449907078*x + 25.000700308137283) * (x^2 - 5.99999017086656*x + 24.999344516841948) * (x^2 - 5.999869379226476*x + 24.99995519346379) * (x^2 - 1.9999999999998566*x + 4.999999999999844)

In [131]:
mat_val = val_of_pol_on_mat(A, x^2 - 5.999999999999998*x + 24.999999999999993)

In [132]:
u,s,v = mat_val.SVD()

In [133]:
s.diagonal()

[65.0,
 17.888543819998308,
 17.888543819998308,
 1.6679986668102624e-14,
 1.4439796873380203e-14,
 1.2914001394611606e-14,
 1.0844771931665232e-14,
 8.998592629397782e-15,
 6.5346074651607245e-15]

In [83]:
find_complex_eigen_vals_with_muls(A)

[[9.999999999999993],
 [1.0000000000000009 + 2.0000000000000004*I],
 [1.0000000000000009 - 2.0000000000000004*I],
 [3.0000000000000018 + 3.999999999999998*I,
  2.999999999999999 + 3.9999999999999982*I],
 [3.0000000000000018 - 3.999999999999998*I,
  2.999999999999999 - 3.9999999999999982*I],
 [2.999999999999999 + 3.9999999999999982*I],
 [2.999999999999999 - 3.9999999999999982*I]]

In [98]:
S = CDF
Sx = PolynomialRing(S, 'x')
x = Sx([0,1])

In [99]:
for el in find_pairs_of_conj_eigvals(A):
    if len(el) == 1:
        continue
    print((x-el[0])*(x-el[1]))
    print()

x^2 - 2.0000000000000018*x + 5.0000000000000036

x^2 - 6.0000000000000036*x + 24.999999999999993

x^2 - 5.999999999999998*x + 24.99999999999998



In [ ]:
(a,b), (a,-b)